version: "3.4"

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

  app:
    depends_on:
      - mongodb
    image: express-crud-mongodb
    environment:
      - DB_HOST=mongodb
    ports:
      - 3000:3000

volumes:
  db:
